### ISSUE TITLE
add info to README about codecov tokens

### ISSUE THREAD

**Issue by TimMonko** [napari/napari-plugin-template#28]
It seems that if you protect your main branch (which Github will recommend), that codecov requires a token. This setting doesn't seem possible to change within codecov. So I think there are many cases where users will need to add their codecov token? It can be added directly to the action, or be stuck in repo secrets. 

Current:
```
      - name: Coverage
        uses: codecov/codecov-action@v2
```
Suggested
```
    - name: Coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: .tox/*/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
```
